lib/sibt_web/router.ex
defmodule SibtWeb.Router do
  use SibtWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SibtWeb.Plugs.SetUser
    plug SibtWeb.Plugs.SetViewRegistry
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SibtWeb do
    pipe_through :browser

    resources "/projects", ProjectController, except: [:show]
    get "/", PageController, :index
    get "/project/:project_code", ProjectController, :show
  end

  scope "/auth", SibtWeb do
    pipe_through :browser

    get "/signout", SessionController, :delete
    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", SibtWeb do
  #   pipe_through :api
  # end
end

lib/sibt_web/views/layout_view.ex
defmodule SibtWeb.LayoutView do
  use SibtWeb, :view
end

lib/sibt_web/templates/layout/_navigation.html.eex
<nav class="flex items-center justify-between flex-wrap bg-grey-lighter p-3 font-sans">
  <div class="flex items-center flex-no-shrink text-grey-darkest mr-6">
    <span class="font-semibold text-xl tracking-tight"><a class="no-underline text-black" href="/">ShouldIBuildThat.io</a></span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-grey-darkest border-grey-darkest" onclick="navbarAccordian()">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto" id="nav">
    <div class="text-sm lg:flex-grow">
    </div>

    <div>
      <%= if @conn.assigns[:user] do %>
       <span class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
            Welcome, <%= @conn.assigns.user.first_name %>!
       </span>
       <%= link "Projects", to: Routes.project_path(@conn, :index), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline" %>
       <%= link "Add Project", to: Routes.project_path(@conn, :new), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline" %>
       <%= link "Sign Out", to: Routes.session_path(@conn, :delete), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline" %>
      <% else %>
       <a href="/auth/facebook" class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
         Sign in with Facebook
       </a>
       <a href="/auth/github" class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
         Sign in with Github
       </a>
      <% end %>
    </div>
  </div>
  <script>
    function navbarAccordian() {
    var x = document.getElementById("nav");
    x.classList.toggle("hidden");
    }
  </script>
</nav>

lib/sibt_web/templates/layout/_notifications.html.eex
<%= if get_flash(@conn, :info) do  %>
    <div class="flex items-center bg-blue text-white text-sm font-bold px-4 py-3 alert" role="alert">
      <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
      <p><%= get_flash(@conn, :info) %><p>
    </div>
<% end %>

<%= if get_flash(@conn, :error) do %>
    <div class="flex items-center bg-red text-white text-sm font-bold px-4 py-3 alert" role="alert">
      <p><%= get_flash(@conn, :error) %><p>
    </div>
<% end %>

lib/sibt_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Sibt · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js"></script>
  </head>
  <body>
    <%= render "_navigation.html", conn: @conn %>
    <main role="main">
      <%= render "_notifications.html", conn: @conn %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>